/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Auth: typeof import('./../components/Auth/index.vue')['default']
    CustomerInfo: typeof import('./../components/company/CustomerInfo.vue')['default']
    FarmerInfo: typeof import('./../components/company/FarmerInfo.vue')['default']
    FileUpload: typeof import('./../components/FileUpload/index.vue')['default']
    FixedActionBar: typeof import('./../components/FixedActionBar/index.vue')['default']
    HButton: typeof import('./../layouts/ui-kit/HButton.vue')['default']
    HCheckList: typeof import('./../layouts/ui-kit/HCheckList.vue')['default']
    HDialog: typeof import('./../layouts/ui-kit/HDialog.vue')['default']
    HDropdown: typeof import('./../layouts/ui-kit/HDropdown.vue')['default']
    HDropdownMenu: typeof import('./../layouts/ui-kit/HDropdownMenu.vue')['default']
    HInput: typeof import('./../layouts/ui-kit/HInput.vue')['default']
    HKbd: typeof import('./../layouts/ui-kit/HKbd.vue')['default']
    HSelect: typeof import('./../layouts/ui-kit/HSelect.vue')['default']
    HSlideover: typeof import('./../layouts/ui-kit/HSlideover.vue')['default']
    HTabList: typeof import('./../layouts/ui-kit/HTabList.vue')['default']
    HToggle: typeof import('./../layouts/ui-kit/HToggle.vue')['default']
    HTooltip: typeof import('./../layouts/ui-kit/HTooltip.vue')['default']
    ImagePreview: typeof import('./../components/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/ImageUpload/index.vue')['default']
    InventoryQuery: typeof import('./../components/wholesale_center/InventoryQuery.vue')['default']
    LoginForm: typeof import('./../components/LoginForm/index.vue')['default']
    MaterialIn: typeof import('./../components/production_base/MaterialIn.vue')['default']
    MaterialInfo: typeof import('./../components/company/MaterialInfo.vue')['default']
    MaterialInfoQuery: typeof import('./../components/production_base/MaterialInfoQuery.vue')['default']
    MaterialInventory: typeof import('./../components/production_base/MaterialInventory.vue')['default']
    MaterialOut: typeof import('./../components/production_base/MaterialOut.vue')['default']
    NotAllowed: typeof import('./../components/NotAllowed/index.vue')['default']
    OriganizationSettings: typeof import('./../components/company/OriganizationSettings.vue')['default']
    PageHeader: typeof import('./../components/PageHeader/index.vue')['default']
    PageMain: typeof import('./../components/PageMain/index.vue')['default']
    PcasCascader: typeof import('./../components/PcasCascader/index.vue')['default']
    ProductIn: typeof import('./../components/production_base/ProductIn.vue')['default']
    ProductInfo: typeof import('./../components/company/ProductInfo.vue')['default']
    ProductInventory: typeof import('./../components/production_base/ProductInventory.vue')['default']
    ProductionInfoQuery: typeof import('./../components/wholesale_center/ProductionInfoQuery.vue')['default']
    ProductionPlanQuery: typeof import('./../components/production_base/ProductionPlanQuery.vue')['default']
    ProductOut: typeof import('./../components/production_base/ProductOut.vue')['default']
    RegisterForm: typeof import('./../components/RegisterForm/index.vue')['default']
    ResetPasswordForm: typeof import('./../components/ResetPasswordForm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesManagement: typeof import('./../components/wholesale_center/SalesManagement.vue')['default']
    SearchBar: typeof import('./../components/SearchBar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    SyetemSettings: typeof import('./../components/company/SyetemSettings.vue')['default']
    SystemInfo: typeof import('./../components/SystemInfo/index.vue')['default']
    Trend: typeof import('./../components/Trend/index.vue')['default']
  }
}
